# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cf499302b71908cc3351dbe3f3e897ae50b4e769292263db8d468dd7f3c2eb81b6c8807a24edb4230489ef06398c6cea03582c83ffeb808bdf69c561ce3c89e

test:
  secret_key_base: 1a698cdb12dfb9fd2e4580c17834c61f8a0a3f16ef9db6fa3c0af6f57ef0a74eba404c0591cc7e3a392c2654594d9675e78bd1e90493d2793328a2cd39863103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
